src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>All</fullName>
        <active>true</active>
        <label>All</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>Seed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Shares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Series_Type__c</fullName>
        <label>Series Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Share_Price__c</fullName>
        <label>Share Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_Company__c</fullName>
        <label>Target Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Investment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Series</label>
    <nameField>
        <displayFormat>Round{00000}</displayFormat>
        <label>Investment Series</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CapTableDHTMLXControllerTest.cls
@IsTest 
public class CapTableDHTMLXControllerTest {

    
    @IsTest
    private static void testgetCapTableData() {
        account a = new account(name='test');
        insert a;
        account a2 = new account(name='test2');
        insert a2;
        account a3 = new account(name='test3');
        insert a3;
        
        CapTableDHTMLXController.AllowEditingUpdate(a.Id,true);
        
        Round__c round = new Round__c();
        round.Target_Company__c= a.id;
        round.Series_Type__c='test';
        round.Share_Price__c=1;
        
        CapTableDHTMLXController.saveNewRound(JSON.serialize(round));
        insert round;
        
        CapTableDHTMLXController.setDollarAmount(a.id,round.id,500,'All');
        CapTableDHTMLXController.setDollarAmount(a.id,round.id,500,'Non-Voting');
        CapTableDHTMLXController.setDollarAmount(a.id,round.id,500,'Voting');
        CapTableDHTMLXController.setShares(a.id,round.id,500,'All');
        CapTableDHTMLXController.setShares(a.id,round.id,500,'Voting');
        CapTableDHTMLXController.setShares(a.id,round.id,500,'Non-Voting');
        CapTableDHTMLXController.setShares(a2.id,round.id,500,'All');

        CapTableDHTMLXController.getCapTableData(a.id,'All','Shares');
        CapTableDHTMLXController.getCapTableData(a.id,'Voting','Dollars');
        CapTableDHTMLXController.getCapTableData(a.id,'Non-Voting','Percentage');
        
        CapTableDHTMLXController.getCapTableData(a.id,'All','Dollars');
        CapTableDHTMLXController.getCapTableData(a.id,'Voting' ,'Shares');
        CapTableDHTMLXController.getCapTableData(a.id,'Non-Voting','Percentage');
        
        CapTableDHTMLXController.getCapTableData(a.id,'All','Percentage');
        CapTableDHTMLXController.getCapTableData(a.id,'Voting','Percentage');
        CapTableDHTMLXController.getCapTableData(a.id,'Non-Voting' ,'Shares');
        CapTableDHTMLXController.setDollarAmount(a.id,round.id,500,'Voting');
        CapTableDHTMLXController.setAllShares(a.id,round.id,500,700);
        CapTableDHTMLXController.setAllShares(a3.id,round.id,500,700);
        system.debug(CapTableDHTMLXController.hasRounds(a.id));
        system.debug(CapTableDHTMLXController.hasRounds(round.id));
        CapTableDHTMLXController.addShareholder(null, 't e s t - 2019', null, 'parent - 2021',  a.id);
        CapTableDHTMLXController.getInvestment(a.id,round.id);

        CapTableDHTMLXController.updateRoundOrder(New List<Round__c>{round});

        CapTableDHTMLXController.importFile('U2VxdWVuY2UgTnVtYmVyLFJlY29yZCBJRCxDaGFydCBvZiBBY2NvdW50cyxDYXRlZ29yeSwzLzI2LzIwMjEsIlExLCAyMDIwIiwiUTIsIDIwMjAiLCJRMywgMjAyMCIsIlE0LCAyMDIwIiwiUTEsIDIwMjEiLCJRMiwgMjAyMSINCjQsYTByMWgwMDAwMDF2dzJUQUFRLGRzNTQsZHNmZHNmZHNmLDQsNCw0LDQsNCw0LDQNCixhMHIxaDAwMDAwMlZaWUtBQTQsaTMsZHNmZHNmZHNmLDAsMCwwLDAsMCwwLDANCixhMHIxaDAwMDAwMkRuYWJBQUMsQVJSLEV4cGVuc2UsMTAuNDUsMjAwLDUsNDAwLDUwMCw5MDAsOTAwDQosYTByMWgwMDAwMDJWWlk1QUFPLEFSUiBZT1ksRXhwZW5zZSwwLDAsMCwwLDAsMCwwDQosYTByMWgwMDAwMDF2dzJSQUFRLGV4cCxFeHBlbnNlLDAs',a.Id, 'All', 'Dollars');
        
        CapTableDHTMLXController.deleteSeries (round.Id);
        CapTableDHTMLXController.deleteShareholder (a.Id,a.Id);
        system.debug(CapTableDHTMLXController.getCommunityAccId());

        CapTableDHTMLXController.fetchLookUpValues('test','Account');
        
        
        
        
        
        }
}