src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Bank_LP</fullName>
        <active>true</active>
        <description>A bank investing in the SBIC</description>
        <label>Bank</label>
    </recordTypes>
    <recordTypes>
        <fullName>prospect</fullName>
        <active>true</active>
        <label>Fintech</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investment__c.object
<CustomObject>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <referenceTo>Round__c</referenceTo>
        <relationshipLabel>Investments</relationshipLabel>
        <relationshipName>Investments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investment</label>
    <nameField>
        <displayFormat>INV{00000}</displayFormat>
        <label>Investment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>Seed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Shares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Series_Type__c</fullName>
        <label>Series Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Company__c</fullName>
        <label>Target Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Investment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Series</label>
    <nameField>
        <displayFormat>Round{00000}</displayFormat>
        <label>Investment Series</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SetSeriesInvExtPBIdTest.cls
@IsTest
public class SetSeriesInvExtPBIdTest {
    @IsTest
    private static void test() {
        Account a = new Account (Name='test', pbk__pbId__c='test',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('prospect').getRecordTypeId());
        insert a;
        a.pbk__pbId__c='accountId';
        a.Updating_By_Skyvia__c = true;
        a.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Bank_LP').getRecordTypeId();
        update a;
        
        Round__c round = new Round__c();
        round.Series_Type__c = 'test';
        round.Target_Company__c = a.Id;
        round.pbk_dealid__c = 'roundId';
        round.pbk_pbId__c = 'accountId';
        insert round;
        
        Investment__c inv = new Investment__c();
        inv.pbk_dealid__c = 'roundId';
        inv.pbk_pbId__c = 'invId';
        inv.Round__c = round.Id;
        insert inv;
        
        round.pbk_pbId__c = 'incorrectId';
        update round;
        
        inv.pbk_dealid__c = 'incorrectId';
        update inv;
    }
}