src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Portfolio_Company</fullName>
        <active>true</active>
        <description>A FinTech company in which Canapi is on the Cap-Table.</description>
        <label>Portfolio Company</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chart_of_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chart of Accounts</relationshipLabel>
        <relationshipName>Chart_of_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chart of Accounts</label>
    <nameField>
        <label>Chart of Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Category__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Categories</relationshipLabel>
        <relationshipName>Financial_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Static</fullName>
                    <default>true</default>
                    <label>Static</label>
                </value>
                <value>
                    <fullName>Calculated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Category</label>
    <nameField>
        <label>Financial Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Report_Period__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Report Periods</relationshipLabel>
        <relationshipName>Report_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Report Period</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Report Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PortfolioCompanyFinancialsTest.cls
@IsTest 
private with sharing class PortfolioCompanyFinancialsTest {
    @IsTest
    private static void test1() {
        Id recordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Portfolio_Company').getRecordTypeId();
        
        account acc =  new Account(
                Name = 'Portfolio Account 1',
                RecordTypeId=recordTypeId
            );
        insert acc;

        integer currentQuarter = ( Date.Today().Month() / 3) + 1;
        String prevQuarter;
        Integer currentYear = System.Today().year();
        String thisQuarter = 'Q' + currentQuarter + ', ' + currentYear;


        Report_Period__c rp = new Report_Period__c();
        rp.quarter__c = thisQuarter;
        rp.Account__c = acc.Id;
        insert rp;

        Financial_Category__c fc = new Financial_Category__c(Name = 'Revenue', Type__c = 'Static', Account__c = acc.Id);
        insert fc;
        
        FinancialsFeatureDHTMLXController.createChartOfAccounts('','ARR', String.ValueOf(fc.Id),'Percentage','',false,'None',null,acc.Id);
        
        Chart_of_Accounts__c chart = [select id from Chart_of_Accounts__c limit 1];
        FF_CalculateFormulas.firstRun = true;
        FinancialsFeatureDHTMLXController.setFinancials(chart.Id, rp.Id,'5','Percentage');

        PortfolioCompanyFinancials.getCapTableData(thisQuarter);
    }
}