src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Target_Commitment__c</fullName>
        <label>Target Commitment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commitment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commitments</relationshipLabel>
        <relationshipName>Commitments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commitment_Stage__c</fullName>
        <label>Commitment Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Commitments</relationshipLabel>
        <relationshipName>Commitments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_Commitment__c</fullName>
        <label>Target Commitment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Commitment</label>
    <nameField>
        <displayFormat>C-{MM}-{YY}-{0000}</displayFormat>
        <label>Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commitments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Canapi_Role__c</fullName>
        <label>Communication Role</label>
        <picklist>
            <picklistValues>
                <fullName>ALL_LPs</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fund__c.object
<CustomObject>
    <fields>
        <fullName>Total_Commitment__c</fullName>
        <label>Total Commitment</label>
        <summarizedField>Commitment__c.Target_Commitment__c</summarizedField>
        <summaryForeignKey>Commitment__c.Fund__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DistributionList.cls
public class DistributionList {
 	@AuraEnabled
    public static String getRecords(){
        List <Account> accList = new List <Account>();
        accList = [select id,name,
                   (select id, Commitment_Stage__c, Target_Commitment__c, Fund__r.name,Fund__r.Total_Commitment__c, Account__r.name from Commitments__r),
                   (select id, FirstName, LastName,Title, email,Account.Name from Contacts)
                  from Account where /*Id IN (SELECT Account__c FROM Commitment__c where Commitment_Stage__c='Interested' or Commitment_Stage__c='Verbal' or Commitment_Stage__c='Letter' or Commitment_Stage__c='Closed' or Commitment_Stage__c='Closing')
                   and */Id IN ( Select AccountId from Contact where Canapi_Role__c includes ('ALL_LPs')) order by name asc
                  ];
        return JSON.serialize(accList);
    }
}