src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Portfolio_Company</fullName>
        <active>true</active>
        <description>A FinTech company in which Canapi is on the Cap-Table.</description>
        <label>Portfolio Company</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chart_of_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chart of Accounts</relationshipLabel>
        <relationshipName>Chart_of_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chart of Accounts</label>
    <nameField>
        <label>Chart of Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Category__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Categories</relationshipLabel>
        <relationshipName>Financial_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Static</fullName>
                    <default>true</default>
                    <label>Static</label>
                </value>
                <value>
                    <fullName>Calculated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Category</label>
    <nameField>
        <label>Financial Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financials__c.object
<CustomObject>
    <fields>
        <fullName>Chart_of_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chart of Accounts</label>
        <referenceTo>Chart_of_Accounts__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Report Period</label>
        <referenceTo>Report_Period__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financials</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Financials  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portfolio_Tab__mdt.object
<CustomObject>
    <fields>
        <fullName>Graph_Type__c</fullName>
        <label>Graph Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bar</fullName>
                    <default>true</default>
                    <label>Bar</label>
                </value>
                <value>
                    <fullName>Line</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_Item_Name__c</fullName>
        <label>Line Item Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Column__c</fullName>
        <label>Portfolio Column</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                    <default>true</default>
                    <label>Currency</label>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Portfolio Tab</label>
    <pluralLabel>Portfolio Tab</pluralLabel>
</CustomObject>

src/objects/Report_Period__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Report Periods</relationshipLabel>
        <relationshipName>Report_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Report Period</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Report Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PortfolioCompanyFinancials.cls
global without sharing class PortfolioCompanyFinancials {

    @RemoteAction @AuraEnabled(cacheable=true)    
    global static CapTableDataDhtmlx getCapTableData(String quarter) {
        
        
        List <Portfolio_Tab__mdt> metadata = [select id, Graph_Type__c, Line_Item_Name__c, Portfolio_Column__c, Type__c from Portfolio_Tab__mdt order by Portfolio_Column__c asc];
        Set <String> portfChaofAccs = new Set <String>();
        
        for (Portfolio_Tab__mdt pmtd: metadata){
            portfChaofAccs.add(pmtd.Line_Item_Name__c);
        }

        List <Account> portfolioAccs = [select id, name from Account where recordtype.DeveloperName = 'Portfolio_Company' order by name asc];
        system.debug(portfolioAccs);
        Set <Id> accIds = new Set <Id> ();
        Map <String,Map <String,List<Financials__c>>> accFinancialsMap = new Map <String,Map <String,List<Financials__c>>>();


        String [] q = quarter.split(', |%2C+');
        integer currentQuarter = Integer.ValueOf(q[0].removeStart('Q'));
        String prevQuarter;
        Integer currentYear = Integer.ValueOf(q[1]);
        String currentYearSearch =  '%'+currentYear+'%';
        String prevYearSearch =  '%'+(currentYear -1) +'%';

        String thisQuarter = 'Q' + currentQuarter + currentYear;
        if (currentQuarter == 1){
            prevQuarter = 'Q4' + String.valueOf(currentYear-1);
        } else {
            prevQuarter = 'Q' + String.valueOf(currentQuarter - 1) + String.valueOf(currentYear);
        }

        for (Account a: portfolioAccs){
            accIds.add(a.Id);
            accFinancialsMap.put(a.Id, New Map <String,List<Financials__c>> ());
        }
                
        List<Financials__c> financials =[
            Select id,
            Chart_of_Accounts__c,
            Chart_of_Accounts__r.Name,
            Report_Period__c,
            Report_Period__r.Quarter__c,
            Chart_of_Accounts__r.Account__c,
            Value__c
            FROM Financials__c
            WHERE  
            Chart_of_Accounts__r.name in : portfChaofAccs
            AND Value__c != null
            AND Report_Period__r.Account__c in: accIds
            AND (Report_Period__r.quarter__c LIKE: currentYearSearch OR Report_Period__r.quarter__c LIKE: prevYearSearch)
            AND Chart_of_Accounts__r.Account__c in: accIds
            AND Chart_of_Accounts__r.Financial_Category__c != null
            order by Chart_of_Accounts__r.Name asc, CreatedDate asc
        ];

        for (Financials__c f: financials){
            if (!accFinancialsMap.get(f.Chart_of_Accounts__r.Account__c).containsKey(f.Chart_of_Accounts__r.Name)){
                accFinancialsMap.get(f.Chart_of_Accounts__r.Account__c).put(f.Chart_of_Accounts__r.Name,new List<Financials__c>());
            } 
            accFinancialsMap.get(f.Chart_of_Accounts__r.Account__c).get(f.Chart_of_Accounts__r.Name).add(f);
        }
        
        
        JSONGenerator generator = JSON.createGenerator(true);
        generator.writeStartObject(); 
        generator.writeFieldName('rows');
        generator.writeStartArray(); 

        List <String> rows = new  List <String> ();
        for (Account a: portfolioAccs){
            generator.writeStartObject(); 
            generator.writeStringField('id', a.Id);
            List<String> strlist = new List<String>();
            //strlist.add(a.Name);
            strlist.add( a.Name  + '^' + '/' + a.Id );

            
            for (Portfolio_Tab__mdt pmtd: metadata){
                boolean isInvestmentFound = false;

                if (accFinancialsMap.containsKey(a.Id) && accFinancialsMap.get(a.Id).containsKey(pmtd.Line_Item_Name__c)){
                    
                    for (Financials__c f: accFinancialsMap.get(a.Id).get(pmtd.Line_Item_Name__c)){
                        if (f.Report_Period__r.Quarter__c.replaceAll(',', '').deleteWhitespace() == thisQuarter){
                            strlist.add(pmtd.Type__c == 'Percent' ? String.valueOf(f.Value__c.SetScale(1)) : String.valueOf(f.Value__c));
                            isInvestmentFound = true;
                            break;
                        }
                        
                    }
                }
                if (!isInvestmentFound && (pmtd.Type__c == 'Currency' || pmtd.Type__c == 'Number')){
                    strlist.add('0.00');
                } else if (!isInvestmentFound && pmtd.Type__c == 'Percent'){
                    strlist.add('0.0');
                }

            }

            generator.writeObjectField('data', strlist);
            generator.writeEndObject(); //Write the end marker of a JSON object '}'
        }
            
        
        generator.writeEndArray(); //Write the end marker of a JSON object ']'
        generator.writeEndObject(); 

        
        
        CapTableDataDhtmlx retData = new CapTableDataDhtmlx((generator.getAsString()),metadata);
        return retData;
        
    }


    global class CapTableDataDhtmlx{
        @AuraEnabled public String data {get;set;}
        @AuraEnabled public List <Portfolio_Tab__mdt> columns {get;set;}
        CapTableDataDhtmlx (String data, List <Portfolio_Tab__mdt> columns){
            this.data = data;
            this.columns = columns;
        }
        
    }
    
}