src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>All</fullName>
        <active>true</active>
        <label>All</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Investment__c.object
<CustomObject>
    <fields>
        <fullName>Investor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investments made by investors (account type investor) linked to a particular round (which then links back to an account_type record = target).</description>
        <label>Investor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investments</relationshipLabel>
        <relationshipName>Investments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <referenceTo>Round__c</referenceTo>
        <relationshipLabel>Investments</relationshipLabel>
        <relationshipName>Investments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investment</label>
    <nameField>
        <displayFormat>INV{00000}</displayFormat>
        <label>Investment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>Seed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Shares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Series_Type__c</fullName>
        <label>Series Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Share_Price__c</fullName>
        <label>Share Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_Company__c</fullName>
        <label>Target Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Investment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Series</label>
    <nameField>
        <displayFormat>Round{00000}</displayFormat>
        <label>Investment Series</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CapTableControllerTest.cls
@IsTest
public class CapTableControllerTest {

    @IsTest
    private static void testSortRoundRecords() {
        
        List<String> orderedRoundNames = new List<String>();
        for (Schema.PicklistEntry pe : Round__c.Round__c.getDescribe().getPicklistValues()) {
            orderedRoundNames.add(pe.getValue());
        }
        
        // build a list in complete backwards order
        List<Round__c> roundsToBeSorted = new List<Round__c>();
        for (Integer i=orderedRoundNames.size()-1; i>-1; i--) {
            roundsToBeSorted.add(
                new Round__c(
                    Round__c = orderedRoundNames[i],
                    Series_Type__c = 'c'
                )
            );
            roundsToBeSorted.add(
                new Round__c(
                    Round__c = orderedRoundNames[i],
                    Series_Type__c = 'a'
                )
            );
        }
        
        List<Round__c> originalUnsortedRounds = roundsToBeSorted.clone();
        
        CapTableController.sortRoundRecords(roundsToBeSorted);
        
        Integer backwardIndex = originalUnsortedRounds.size()-1;
        for (Integer i=0; i<roundsToBeSorted.size(); i++) {
            System.assertEquals(originalUnsortedRounds[backwardIndex].Round__c, roundsToBeSorted[i].Round__c);
            System.assertEquals(originalUnsortedRounds[backwardIndex].Series_Type__c, roundsToBeSorted[i].Series_Type__c);
            backwardIndex--;
        }
    }
    @IsTest
    private static void testgetCapTableData() {
        account a = new account(name='test');
        insert a;
        
        Round__c round = new Round__c();
        round.Target_Company__c= a.id;
        round.Series_Type__c='test';
        round.Share_Price__c=1;
        insert round;
        
        CapTableController.setDollarAmount(a.id,round.id,500,'All');
        CapTableController.setDollarAmount(a.id,round.id,500,'Non-Voting');
        CapTableController.setDollarAmount(a.id,round.id,500,'Voting');
        CapTableController.setShares(a.id,round.id,500,700);
        
        /*Investment__c inv = new Investment__c();
        inv.Investor__c=a.id;
        inv.Round__c=round.id;
        insert inv;*/
        
        CapTableController.getCapTableData(a.id,'All');
        CapTableController.getCapTableData(a.id,'Voting');
        CapTableController.getCapTableData(a.id,'Non-Voting');
        CapTableController.setDollarAmount(a.id,round.id,500,'Voting');
        CapTableController.setShares(a.id,round.id,500,700);
        system.debug(CapTableController.hasRounds(a.id));
        CapTableController.addShareholder(a.id,'t e s t - 2019',a.id);
        
        CapTableController.deleteSeries (round.Id);
        CapTableController.deleteShareholder (a.Id,a.Id);
        system.debug(CapTableController.getCommunityAccId());
        
        
        }
}