src/objects/Alliance_Announcement__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiration_date__c</fullName>
        <label>Expiration date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Headline__c</fullName>
        <label>Headline</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_date__c</fullName>
        <label>Release date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Alliance Announcement</label>
    <nameField>
        <displayFormat>AA - {0000}</displayFormat>
        <label>Alliance Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alliance Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AllianceAnnouncements.cls
public without sharing class AllianceAnnouncements {
	@AuraEnabled
    public static List<Alliance_Announcement__c> getNews() {
        return [SELECT Id, Body__c,Headline__c,Release_date__c FROM Alliance_Announcement__c 
                where Release_date__c <=: Datetime.now() and (Expiration_date__c >: Datetime.now() or Expiration_date__c  = null) order by Release_date__c desc LIMIT 50000];
    }
}