src/objects/Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Review_Type__c</fullName>
        <label>Review Type</label>
        <picklist>
            <picklistValues>
                <fullName>tech_review_deep_dive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Review (periodic)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial_Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology Review (Prospect)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Due Diligence Checklist</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Due Diligence Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/review_item__c.object
<CustomObject>
    <description>A list of all technology assets that are part of an initial technology due dilligence process.</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Due Diligence Checklist Number</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Review Items</relationshipLabel>
        <relationshipName>Review_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assets_Needed__c</fullName>
        <description>This is the list of assets need for the review item. If left blank, the users can provide any documentation they deem fit that answers the review item.</description>
        <inlineHelpText>This is the list of assets need for the review item. If left blank, the users can provide any documentation they deem fit that answers the review item.</inlineHelpText>
        <label>Assets Needed</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Item_Category_Description__c</fullName>
        <label>Item Category Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Category__c</fullName>
        <defaultValue>&quot;other&quot;</defaultValue>
        <label>Item Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Review_Item_Name__c</fullName>
        <label>Review Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Review Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Review Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/review_item_meta__mdt.object
<CustomObject>
    <description>Works with the default technology assets.</description>
    <fields>
        <fullName>Category_Description__c</fullName>
        <label>Category Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Assets__c</fullName>
        <label>Item Assets</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rvw_type__c</fullName>
        <label>Review Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>review_Category__c</fullName>
        <label>Review Category</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Review Item</label>
    <pluralLabel>Review Items</pluralLabel>
</CustomObject>

src/classes/NewTechnicalReviewTest.cls
@isTest
private class NewTechnicalReviewTest {
    static testMethod void verifyTechnicalAssets() {
    
        List<Assessment__c> reviews = [select id from Assessment__c limit 1];
        List<review_item_meta__mdt> reviewItems = [select id, 	MasterLabel , DeveloperName, Rvw_type__c, review_Category__c, Category_Description__c, Item_Assets__c, Item_Description__c from review_item_meta__mdt];
        
        Test.startTest();
       	for (Assessment__c review : reviews) {
            if (review.Review_Type__c == 'Technical Review (initial)') {
                
                for (review_item_meta__mdt r:reviewItems) {
                	review_item__c ri = new review_item__c();
                    ri.Assessment__c = review.Id;
                    ri.Assets_Needed__c = r.Item_Assets__c;
                    ri.Item_Category__c = r.review_Category__c;
                    ri.Item_Category_Description__c = 	r.Category_Description__c;
                    ri.Item_Description__c = r.Item_Description__c;
                    ri.Review_Item_Name__c = r.MasterLabel;
                    insert ri;
                    }
                Test.stopTest();
                  
            }

        System.assertNotEquals(reviews, null);
 

    }
    }
}