src/objects/Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The company that is the subject of the assessment.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assessments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Due Diligence Checklist</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Due Diligence Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/review_item__c.object
<CustomObject>
    <description>A list of all technology assets that are part of an initial technology due dilligence process.</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Due Diligence Checklist Number</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Review Items</relationshipLabel>
        <relationshipName>Review_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Category_Description__c</fullName>
        <label>Item Category Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Category__c</fullName>
        <defaultValue>&quot;other&quot;</defaultValue>
        <label>Item Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Item_Name__c</fullName>
        <label>Review Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Review Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Review Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountReviewItemsDHTMLXControllerTest.cls
@IsTest
public class AccountReviewItemsDHTMLXControllerTest {
    @IsTest
    private static void test1() {
        Account acc = new Account(Name = 'Canapi');
        insert acc;

        Assessment__c assess = new Assessment__c(Account__c = acc.id);
        insert assess;

        
        review_item__c ri = new review_item__c(
                Assessment__c = assess.Id, 
                Review_Item_Name__c = 'Bronze 1',
                Item_Category__c = 'Bronze',
                Item_Category_Description__c = 'Bronze items');
            
        insert ri;

        
        AccountReviewItemsDHTMLXController.setRIData(ri.id,'test','test','test', 'test', '1','Pending', 'test');
        List <String> statuses = new List <String>{'Pending'};
        Document__c doc = new Document__c (Name__c='test',Account__c=acc.Id);
        insert doc;

        Review_Items_Controller.LinkDocToRI(ri.Id, doc.Id, 'test');

        AccountReviewItemsDHTMLXController.createCategory('someCat', assess.Id);
        AccountReviewItemsDHTMLXController.GetCategoryData('someCat', assess.Id);
        AccountReviewItemsDHTMLXController.setCatData('someCat', 'test', 'newcatName', assess.Id);


        AccountReviewItemsDHTMLXController.GetReviewItemsList(assess.Id,JSON.serialize(statuses),'');
        AccountReviewItemsDHTMLXController.getRIData(ri.id);
        AccountReviewItemsDHTMLXController.getWrapper(ri.id);
        AccountReviewItemsDHTMLXController.saveRecord(JSON.serialize(ri));
        AccountReviewItemsDHTMLXController.setCompleted(ri.id);

        AccountReviewItemsDHTMLXController.removeJunctionObjectById(String.valueOf(ri.Id) + String.valueOf(doc.Id));
        AccountReviewItemsDHTMLXController.GetAllDDchecklists(acc.Id);
        AccountReviewItemsDHTMLXController.getInitValuesWrapper(acc.Id);
        AccountReviewItemsDHTMLXController.getInitValuesWrapper(assess.Id);
        AccountReviewItemsDHTMLXController.getInitValuesWrapper(null);

        AccountReviewItemsDHTMLXController.removeRIById(ri.Id);
        AccountReviewItemsDHTMLXController.removeCategoryByName('newcatName',assess.Id);
        AccountReviewItemsDHTMLXController.removeDDById(assess.Id);

    }

}