src/objects/Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The company that is the subject of the assessment.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assessments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Due Diligence Checklist</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Due Diligence Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/review_item__c.object
<CustomObject>
    <description>A list of all technology assets that are part of an initial technology due dilligence process.</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Due Diligence Checklist Number</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Review Items</relationshipLabel>
        <relationshipName>Review_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <description>Used by the custom Assessment Review Items Lightning component to determine whether the record should be read-only for the current user.</description>
        <formula>$Profile.Name = &quot;Community: Portfolio Company&quot; &amp;&amp; NOT(Assessment__r.Is_Current_User_a_Reviewer__c) &amp;&amp; (ISPICKVAL(Review_Item_Status__c, &quot;In File&quot;) || ISPICKVAL(Review_Item_Status__c, &quot;In Process&quot;) || ISPICKVAL(Review_Item_Status__c, &quot;Complete&quot;))</formula>
        <inlineHelpText>Is the Review Item record read-only for the current user due to Review Item Status?</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Category_Description__c</fullName>
        <label>Item Category Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Category__c</fullName>
        <defaultValue>&quot;other&quot;</defaultValue>
        <label>Item Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Item_Name__c</fullName>
        <label>Review Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Item_Status__c</fullName>
        <label>Review Item Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Review Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Review Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContentDocumentTriggerTest.cls
@isTest
public class ContentDocumentTriggerTest {

    @testSetup 
    private static void testDataSetup() {
        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Assessment__c assess = new Assessment__c(Account__c = acc.id);
        insert assess;

        review_item__c item = new review_item__c(
            Assessment__c = assess.Id, 
            Review_Item_Name__c = 'Gold 1',
            Item_Category__c = 'Gold',
            Item_Category_Description__c = 'Gold items');
        insert item;

        ContentVersion cv = new ContentVersion(
            Title = 'Test Review Item File',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Review Item File'),
            IsMajorVersion = true
        );
        insert cv;
        
        ContentDocument cd = [
            SELECT Id, Title, LatestPublishedVersionId 
            FROM ContentDocument
            WHERE LatestPublishedVersionId = :cv.Id
        ];

        ContentDocumentLink cdl = New ContentDocumentLink(
            LinkedEntityId = item.Id,
            ContentDocumentId = cd.Id,
            shareType = 'V'
        );
        insert cdl;

        ContentVersion cv2 = new ContentVersion(
            Title = 'Test Account File',
            PathOnClient = 'PolarBears.jpg',
            VersionData = Blob.valueOf('Test Account File'),
            IsMajorVersion = true
        );
        insert cv2;
        
        ContentDocument cd2 = [
            SELECT Id, Title, LatestPublishedVersionId 
            FROM ContentDocument
            WHERE LatestPublishedVersionId = :cv2.Id
        ];

        ContentDocumentLink cdl2 = New ContentDocumentLink(
            LinkedEntityId = acc.Id,
            ContentDocumentId = cd2.Id,
            shareType = 'V'
        );
        insert cdl2;
    }

    @isTest
    private static void deleteReviewItemFileTest() {
        review_item__c reviewItem = [
            SELECT Id, Review_Item_Status__c, Is_Locked__c
            FROM review_item__c
            LIMIT 1
        ];

        ContentDocumentLink cdl = [
            SELECT ContentDocumentId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :reviewItem.Id
            LIMIT 1
        ];

        ContentDocument cd = [
            SELECT Id, Title
            FROM ContentDocument
            WHERE Id = :cdl.ContentDocumentId
        ];

        Boolean isReviewItemLocked = reviewItem.Is_Locked__c;
        Boolean wasDeleteSuccessful = false;

        Test.startTest();
        try {
            delete cd;
            wasDeleteSuccessful = true;
        }
        catch (Exception ex) {
            wasDeleteSuccessful = false;
        }
        Test.stopTest();

        System.assertNotEquals(isReviewItemLocked, wasDeleteSuccessful);
    }

    @isTest 
    private static void deleteNonReviewItemFileTest() {
        Account acc = [
            SELECT Id
            FROM Account
            LIMIT 1
        ];

        ContentDocumentLink cdl = [
            SELECT ContentDocumentId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :acc.Id
            LIMIT 1
        ];

        ContentDocument cd = [
            SELECT Id, Title
            FROM ContentDocument
            WHERE Id = :cdl.ContentDocumentId
        ];

        Boolean wasDeleteSuccessful = false;

        Test.startTest();
        try {
            delete cd;
            wasDeleteSuccessful = true;
        }
        catch (Exception ex) {
            wasDeleteSuccessful = false;
        }
        Test.stopTest();

        System.assert(wasDeleteSuccessful);
    }
}