src/objects/Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The company that is the subject of the assessment.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assessments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <label>Due Diligence Checklist</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Due Diligence Checklist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Board_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Board Meetings</relationshipLabel>
        <relationshipName>Board_Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Board Meeting</label>
    <nameField>
        <displayFormat>{MM}-{DD}-{YY}-{00}</displayFormat>
        <label>Board Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Report__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Reports</relationshipLabel>
        <relationshipName>Financial_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Report</label>
    <nameField>
        <displayFormat>FR-{00000000}</displayFormat>
        <label>Financial Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/review_item__c.object
<CustomObject>
    <description>A list of all technology assets that are part of an initial technology due dilligence process.</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <label>Due Diligence Checklist Number</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Review Items</relationshipLabel>
        <relationshipName>Review_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assets_Needed__c</fullName>
        <description>This is the list of assets need for the review item. If left blank, the users can provide any documentation they deem fit that answers the review item.</description>
        <inlineHelpText>This is the list of assets need for the review item. If left blank, the users can provide any documentation they deem fit that answers the review item.</inlineHelpText>
        <label>Assets Needed</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>File_Count__c</fullName>
        <label>File Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finished__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this review item is complete, please check this box to indicate you are finished with it and it&apos;s ready to be reviewed.</inlineHelpText>
        <label>Finished</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grade_Description__c</fullName>
        <description>Why was that grade given?</description>
        <label>Grade Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Grade_Number__c</fullName>
        <description>This field converts the picklist of Grade to a number value for use in calculations.</description>
        <formula>VALUE(TEXT( Item_Grading__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grade Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Locked__c</fullName>
        <description>Used by the custom Assessment Review Items Lightning component to determine whether the record should be read-only for the current user.</description>
        <formula>$Profile.Name = &quot;Community: Portfolio Company&quot; &amp;&amp; NOT(Assessment__r.Is_Current_User_a_Reviewer__c) &amp;&amp; (ISPICKVAL(Review_Item_Status__c, &quot;In File&quot;) || ISPICKVAL(Review_Item_Status__c, &quot;In Process&quot;) || ISPICKVAL(Review_Item_Status__c, &quot;Complete&quot;))</formula>
        <inlineHelpText>Is the Review Item record read-only for the current user due to Review Item Status?</inlineHelpText>
        <label>Is Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Category_Description__c</fullName>
        <label>Item Category Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Category__c</fullName>
        <defaultValue>&quot;other&quot;</defaultValue>
        <label>Item Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Comments__c</fullName>
        <description>A large area where someone can describe the answer to the question (item description) that is asked.</description>
        <label>Item Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <label>Item Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Item_Grading__c</fullName>
        <description>Asset grade: 1 is the worst and 3 is the best.</description>
        <label>Item Grading</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
                <color>#009900</color>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <description>Date the documentation was reviewed by the fund tech team.</description>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Item_Name__c</fullName>
        <label>Review Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Item_Status__c</fullName>
        <label>Review Item Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Review_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Urgent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marks whether or not this is an urgent item.</description>
        <inlineHelpText>Marks whether or not this is an urgent item.</inlineHelpText>
        <label>Urgent</label>
        <type>Checkbox</type>
    </fields>
    <label>Review Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Review Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>Seed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Shares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Company__c</fullName>
        <label>Target Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Investment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Series</label>
    <nameField>
        <displayFormat>Round{00000}</displayFormat>
        <label>Investment Series</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountReviewItemsDHTMLXController.cls
global with sharing class AccountReviewItemsDHTMLXController {
    @RemoteAction
    global static List <Review_Item__c> getReviewItems(String recId) {
        List<Review_Item__c> reviewItems = [
            SELECT
                Id,
                Name,
                Assets_Needed__c,
            	File_Count__c,
            	Item_Comments__c,
                Grade_Number__c,
                Urgent__c,
                Item_Grading__c,
                Grade_Description__c,
            	Assessment__c,
            	Assessment__r.Name,
            	Review_Date__c,
                Item_Category__c,
                Item_Category_Description__c,
                Item_Description__c,
                Finished__c,
                Review_Item_Name__c,
                Review_Item_Status__c
            FROM Review_Item__c
            WHERE Assessment__c = :recId
            ORDER BY Item_Category__c ASC NULLS LAST, Name ASC
        ];
        return reviewItems;
    }

    @RemoteAction
     global static List <Assessment__c> GetAccountsRelatedLists (String recId){
         /*if(id.valueOf(recId).getSObjectType().getDescribe().getName()=='Contact'){
             recId = [select id, AccountId from Contact where id=:recId].AccountId;
         }
         if(id.valueOf(recId).getSObjectType().getDescribe().getName()=='Opportunity'){
             recId = [select id, AccountId from Opportunity where id=:recId].AccountId;
         }
         if(id.valueOf(recId).getSObjectType().getDescribe().getName()=='Board_Meeting__c'){
             recId = [select id, Account__c from Board_Meeting__c where id=:recId].Account__c;
         }
         if (id.valueOf(recId).getSObjectType().getDescribe().getName()=='Financial_Report__c'){
             recId = [select id, Account__c from Financial_Report__c where id=:recId].Account__c;
         }
         if (id.valueOf(recId).getSObjectType().getDescribe().getName()=='Round__c'){
             recId = [select id, Target_Company__c from Round__c where id=:recId].Target_Company__c;
         }
         if (id.valueOf(recId).getSObjectType().getDescribe().getName()=='Task'){
             recId = [SELECT Id, AccountId from Task where id=:recId].AccountId;
         }
        */
         recId = [SELECT Id, Account__c from Assessment__c where id=:recId].Account__c;
         //Account a = [select Id,name,(select id,name from opportunities order by name asc), (select id, name from contacts order by name asc),(select id, name from Board_Meetings__r order by Date__c desc nulls last) from Account where id=:recId];
         return [select id, Name, Account__r.Name, (select id, Item_Category__c from Review_Items__r order by Item_Category__c nulls last) from Assessment__c where Account__c =: recId];
     }

     @RemoteAction
    global static String GetRIFiltered(String DDId, String category){
        JSONGenerator generator = JSON.createGenerator(true);
            generator.writeStartObject(); 
            generator.writeFieldName('rows');
            generator.writeStartArray(); 
            for (Review_Item__c ri: [select Id, Name, Assets_Needed__c, File_Count__c, Item_Comments__c, Grade_Number__c, Urgent__c, Item_Grading__c, Grade_Description__c, Assessment__c, Assessment__r.Name, Review_Date__c, Item_Category__c, Item_Category_Description__c, Item_Description__c, Finished__c, Review_Item_Name__c, Review_Item_Status__c FROM Review_Item__c WHERE Assessment__c = :DDId and  Item_Category__c =: category ORDER BY Review_Item_Name__c ASC]){
                generator.writeStartObject(); //Write the starting marker of a JSON object '{'
                generator.writeStringField('id', ri.Id);
                List<String> strlist = new List<String>();
                strlist.add(ri.Review_Item_Name__c);
                strlist.add(ri.Review_Item_Status__c);
                strlist.add(ri.Assets_Needed__c);
                strlist.add('clip.png^Attach^javascript:sendToParent(' + '"link","' + ri.Id + '");^_self');
                strlist.add('edit.png^Attach^javascript:sendToParent(' + '"edit","' + ri.Id + '");^_self');
                generator.writeObjectField('data', strlist);
                generator.writeEndObject();
            }
        generator.writeEndArray(); //Write the end marker of a JSON object ']'
        generator.writeEndObject();
        return generator.getAsString();
    }

    @RemoteAction
    global static Review_Item__c getRIData(String recId){
        return [select id, Item_Description__c, Item_Comments__c, Grade_Description__c, Review_Item_Name__c FROM Review_Item__c WHERE id = :recId];
    }

    @RemoteAction
    global static void setRIData(String recId, String itemComments, String GradeDescription){
        Review_Item__c ri = new Review_Item__c(id = recId, Item_Comments__c = itemComments, Grade_Description__c = GradeDescription);
        update ri;
    }


    @AuraEnabled  
    public static RIwrapper getWrapper(String riID) {
        system.debug(riID);
        Review_Item__c reviewItem = [SELECT Is_Locked__c, Id,Name,Assets_Needed__c,File_Count__c,Item_Comments__c,Grade_Number__c,Urgent__c,Item_Grading__c,Grade_Description__c,Assessment__c,Assessment__r.Name,Review_Date__c,Item_Category__c,Item_Category_Description__c,Item_Description__c,Finished__c,Review_Item_Name__c, Review_Item_Status__c FROM Review_Item__c where id =: riID limit 1];
        List<UserRecordAccess> access = [
            SELECT RecordId, HasEditAccess, MaxAccessLevel 
            FROM UserRecordAccess 
            WHERE UserId = :UserInfo.getUserId() 
            AND RecordId = :riID
        ];

        Boolean editable = !access.isEmpty() && access[0].HasEditAccess && !reviewItem.Is_Locked__c;
        Boolean isCreateable = new CheckObjectPermissionsInVisualForce('review_item__c').isCreateable();
        return new RIwrapper (reviewItem, editable, isCreateable);
    }

    @AuraEnabled
    public static Boolean isReviewItemCreateable() {
        // below is the desired method of checking permissions, but it always returns true due to
        // known issue W-2616683 where Apex can't correctly determine the current user's access because 
        // the code runs in system mode. for now using VisualForce workaround as decribed at:
        //   https://success.salesforce.com/issues_view?id=a1p300000008djFAAQ
        // Boolean isCreateable = Schema.describeSObjects(new List<String>{'review_item__c'})[0].isCreateable();
        Boolean isCreateable = new CheckObjectPermissionsInVisualForce('review_item__c').isCreateable();
        System.debug('+++ isCreateable: ' + isCreateable);
        return isCreateable;
    }

    @AuraEnabled
    public static void saveRecord (String RIrec){
        RIrec=RIrec.replace('[','').replaceAll(']','');
        system.debug(RIrec);
        Review_Item__c ri = (Review_Item__c)JSON.deserialize(RIrec,Review_Item__c.class);
        
        update ri;
    }

    public class RIwrapper {
        @AuraEnabled
        public Review_Item__c reviewItem {get; set;}
        @AuraEnabled
        public Boolean isRecordEditable {get; set;}
        @AuraEnabled
        public Boolean isReviewItemCreateable {get; set;}
        public RIwrapper(Review_Item__c reviewItem, boolean isRecordEditable, boolean isReviewItemCreateable){
            this.reviewItem = reviewItem;
            this.isRecordEditable = isRecordEditable;
            this.isReviewItemCreateable = isReviewItemCreateable;
        }
    }

}