src/objects/Board_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Board Meetings</relationshipLabel>
        <relationshipName>Board_Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Board Meeting</label>
    <nameField>
        <displayFormat>{MM}-{DD}-{YY}-{00}</displayFormat>
        <label>Board Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Board Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Board_Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Board Meeting</label>
        <referenceTo>Board_Meeting__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DocumentsSharedWithAPusers.cls
public without sharing class DocumentsSharedWithAPusers {
    @AuraEnabled
    public static List<Document__c> getSharings() {

        String apGroupId = [select id from Group where Name = 'Alliance Portal Users' limit 1].id;
        
        Set <id> ParentIds = new Set <id>();
        for (Document__Share  ds: [select id,UserOrGroupId,RowCause,ParentId from Document__Share where UserOrGroupId =: apGroupId and RowCause!= 'Owner']){
            ParentIds.add(ds.ParentId);
        }
        List <Document__c> docList = new List <Document__c>();
        docList = [select id, Name__c, Owner.Name,CreatedDate, OwnerId,Contact__c,Contact__r.Name,Account__c,Account__r.Name,Board_Meeting__c,Board_Meeting__r.Name from Document__c where id in: ParentIds order by CreatedDate desc];

        return docList;
         }
}