src/objects/Chart_of_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chart of Accounts</relationshipLabel>
        <relationshipName>Chart_of_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chart of Accounts</label>
    <nameField>
        <label>Chart of Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financials__c.object
<CustomObject>
    <fields>
        <fullName>Chart_of_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chart of Accounts</label>
        <referenceTo>Chart_of_Accounts__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Report Period</label>
        <referenceTo>Report_Period__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financials</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Financials  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financials Change Requests</relationshipLabel>
        <relationshipName>Financials_Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Financials_Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financials Change Request</label>
    <nameField>
        <displayFormat>FCR - {00000}</displayFormat>
        <label>Financials Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials_Verification__c.object
<CustomObject>
    <fields>
        <fullName>DateValue__c</fullName>
        <label>DateValue</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financials_Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financials Change Request</label>
        <referenceTo>Financials_Change_Request__c</referenceTo>
        <relationshipLabel>Financials Verifications</relationshipLabel>
        <relationshipName>Financials_Verifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financials__c</fullName>
        <label>Financials</label>
        <referenceTo>Financials__c</referenceTo>
        <relationshipLabel>Financials Verifications</relationshipLabel>
        <relationshipName>Financials_Verifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financials Verification</label>
    <nameField>
        <displayFormat>FV-{00000}</displayFormat>
        <label>Financials Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Verifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Report_Period__c.object
<CustomObject>
    <label>Report Period</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Report Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FinancialsRequestReportController.cls
public with sharing class FinancialsRequestReportController {
    private final Financials_Change_Request__c FCR;

    public FinancialsRequestReportController(ApexPages.StandardController controller) {
        //this.FCR = (Financials_Change_Request__c)controller.getRecord();
        Id fcrId = (Id) System.currentPageReference().getParameters().get('id');  
        system.debug(System.currentPageReference().getParameters().get('id'));
        //system.debug((Financials_Change_Request__c)controller.getRecord());
        this.FCR = [SELECT 
        Id,
        Account__c,
        Account__r.Name,
        Requestor__r.Name,
        Requestor__c,
        CreatedDate
         FROM Financials_Change_Request__c WHERE Id = :fcrId];
    }

    public List <Financials_Verification__c> getVerifications() {
        return [
            select id, 
            Financials__r.Chart_of_Accounts__r.Name, 
            Financials__r.Chart_of_Accounts__r.Type__c,
            Financials__r.Report_Period__r.Quarter__c,
            Value__c,
            Financials__r.Value__c,
            TextValue__c,
            Financials__r.TextValue__c,
            DateValue__c,
            Financials__r.DateValue__c
            from Financials_Verification__c
            where Financials_Change_Request__c=: FCR.Id 
            order by Financials__r.Report_Period__r.Quarter__c, Financials__r.Chart_of_Accounts__r.Name
            ];
    }

}