src/objects/Chart_of_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chart of Accounts</relationshipLabel>
        <relationshipName>Chart_of_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chart of Accounts</label>
    <nameField>
        <label>Chart of Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financials__c.object
<CustomObject>
    <fields>
        <fullName>Chart_of_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chart of Accounts</label>
        <referenceTo>Chart_of_Accounts__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financials</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Financials  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financials Change Requests</relationshipLabel>
        <relationshipName>Financials_Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Financials_Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financials Change Request</label>
    <nameField>
        <displayFormat>FCR - {00000}</displayFormat>
        <label>Financials Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials_Verification__c.object
<CustomObject>
    <fields>
        <fullName>DateValue__c</fullName>
        <label>DateValue</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financials_Change_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financials Change Request</label>
        <referenceTo>Financials_Change_Request__c</referenceTo>
        <relationshipLabel>Financials Verifications</relationshipLabel>
        <relationshipName>Financials_Verifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financials__c</fullName>
        <label>Financials</label>
        <referenceTo>Financials__c</referenceTo>
        <relationshipLabel>Financials Verifications</relationshipLabel>
        <relationshipName>Financials_Verifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Request_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>TextValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financials Verification</label>
    <nameField>
        <displayFormat>FV-{00000}</displayFormat>
        <label>Financials Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Verifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FinancialsCreateRequestBatch.cls
global class FinancialsCreateRequestBatch implements Database.Batchable<sobject>, Database.Stateful, Database.AllowsCallouts{
    Map <String,List<Financials_Verification__c>> reqMap = new Map <String,List<Financials_Verification__c>>();
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id, CreatedByID, CreatedBy.Name, Value__c, TextValue__c, DateValue__c,Financials__c, Financials__r.Chart_of_Accounts__r.Account__r.Name, Financials__r.Chart_of_Accounts__r.Account__c, Financials__r.Value__c, Financials__r.TextValue__c,  Financials__r.DateValue__c FROM Financials_Verification__c where Request_Created__c = false');
    }   
    global void execute(Database.BatchableContext bc, List<Financials_Verification__c> fins){
        for(Financials_Verification__c f : fins){
           if (reqMap.containsKey('' + f.CreatedByID + f.Financials__r.Chart_of_Accounts__r.Account__c)){
                List<Financials_Verification__c> finMapList = reqMap.get('' + f.CreatedByID + f.Financials__r.Chart_of_Accounts__r.Account__c); 
                finMapList.add(f);
                reqMap.put('' + f.CreatedByID + f.Financials__r.Chart_of_Accounts__r.Account__c, finMapList); 
           } else {
            reqMap.put('' + f.CreatedByID + f.Financials__r.Chart_of_Accounts__r.Account__c, new List<Financials_Verification__c> {f}); 
           }
        }
    }
        global void finish(Database.BatchableContext bc){
            //Financials_Change_Request__c
            system.debug(reqMap.size());
            List <Financials_Change_Request__c> fcrList = new List <Financials_Change_Request__c>();
            for(String keys: reqMap.KeySet()){
                fcrList.add(new Financials_Change_Request__c(
                    Account__c = reqMap.get(keys)[0].Financials__r.Chart_of_Accounts__r.Account__c,
                    Requestor__c = reqMap.get(keys)[0].CreatedById
                    ));
            }
            insert fcrList;
            integer i = 0;
            List <Financials_Verification__c> finForUpdate = new List <Financials_Verification__c>();
            Set <String> reqIds = new Set <String>();
            for(String keys: reqMap.KeySet()){
                                    
                for (Financials_Verification__c fin: reqMap.get(keys)){
                    fin.Financials_Change_Request__c = fcrList[i].Id;
                    fin.Request_Created__c = true;
                    finForUpdate.add(fin);
                }

                Approval.ProcessSubmitRequest req1 = 
                    new Approval.ProcessSubmitRequest();
                //req1.setComments('Submitting request for approval.');
                req1.setObjectId(fcrList[i].Id);
                reqIds.add(fcrList[i].Id);
                
                // Submit on behalf of a specific submitter
                //req1.setSubmitterId(user1.Id); 
                
                // Submit the record to specific process and skip the criteria evaluation
                //req1.setProcessDefinitionNameOrId('PTO_Request_Process');
                req1.setSkipEntryCriteria(true);
                
                // Submit the approval request for the account
                Approval.ProcessResult result = Approval.process(req1);
                
                i++;
            }
            update finForUpdate;

            
            FinancialsSaveRequestBatch b = new FinancialsSaveRequestBatch();
            Database.executeBatch(b, 50);
    }


}