src/objects/Chart_of_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chart of Accounts</relationshipLabel>
        <relationshipName>Chart_of_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chart of Accounts</label>
    <nameField>
        <label>Chart of Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Chart_of_Accounts_Template__c.object
<CustomObject>
    <label>Chart of Accounts Template</label>
    <nameField>
        <displayFormat>CHT - {0000}</displayFormat>
        <label>Chart of Accounts Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chart of Accounts Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials__c.object
<CustomObject>
    <fields>
        <fullName>Chart_of_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chart of Accounts</label>
        <referenceTo>Chart_of_Accounts__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Report Period</label>
        <referenceTo>Report_Period__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financials</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Financials  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Report_Period__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Report Periods</relationshipLabel>
        <relationshipName>Report_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Report Period</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Report Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FinancialsFeatureDHTMLXControllerTest.cls
@IsTest
public class FinancialsFeatureDHTMLXControllerTest {
    
    @testSetup static void setup() {
        Account acc = new Account(Name = 'Test Account');
        insert acc; 
        Report_Period__c rp = new Report_Period__c();
        rp.Date__c = system.today();
        rp.Account__c = acc.Id;
        insert rp;
        
        FinancialsFeatureDHTMLXController.createChartOfAccounts('test1', 'Revenue','',null,acc.Id);
        
        Chart_of_Accounts__c chart = [select id from Chart_of_Accounts__c limit 1];
        FF_CalculateFormulas.firstRun = true;
        FinancialsFeatureDHTMLXController.setFinancials(chart.Id, rp.Id,5);
        FF_CalculateFormulas.firstRun = true;
    }
    
    @IsTest
    private static void test1() {
        /*Account acc = [select id from account];*/
        Account acc = new Account(Name = 'Canapi');
        insert acc;
        
        Report_Period__c rp = new Report_Period__c();
        rp.Date__c = system.today();
        rp.Account__c = acc.Id;
        FinancialsFeatureDHTMLXController.createReportPeriod(JSON.serialize(rp), acc.Id, '');
        insert rp;
        
        
        FF_CalculateFormulas.firstRun = true;
        FinancialsFeatureDHTMLXController.createChartOfAccounts('test2', 'Metric','{test1}*2',null,acc.Id);
        FF_CalculateFormulas.firstRun = true;
        FinancialsFeatureDHTMLXController.createChartOfAccounts('test2', 'Metric','{test1}*2',null,acc.Id);
        
        Chart_of_Accounts__c chart = [select id from Chart_of_Accounts__c limit 1];

        FinancialsFeatureDHTMLXController.setFinancials(chart.Id, rp.Id, 1);
        FinancialsFeatureDHTMLXController.setFinancials(chart.Id, rp.Id, 2);
        
        FinancialsFeatureDHTMLXController.AllowEditingUpdate (acc.Id, true);
        
        FinancialsFeatureDHTMLXController.getCapTableData('');

        FinancialsFeatureDHTMLXController.createTemplate('test', acc.Id);
        FinancialsFeatureDHTMLXController.createTemplate('test', acc.Id);
        String templId = [select id from Chart_of_Accounts_Template__c limit 1].Id;
        FinancialsFeatureDHTMLXController.applyTemplate(templId, acc.Id);
        FinancialsFeatureDHTMLXController.getTemplatesData();
        FinancialsFeatureDHTMLXController.getTemplatesPreview(templId);
        FinancialsFeatureDHTMLXController.getSavedTemplates();
        FinancialsFeatureDHTMLXController.deleteTemplate(templId);
        
        FinancialsFeatureDHTMLXController.deleteChartOfAccounts(chart.Id);
        FinancialsFeatureDHTMLXController.deleteReportPeriod(rp.Id);
        
    }
	
    @IsTest
    private static void test2() {
        //Financials__c fin = new Financials__c();
        
    }
}