src/objects/Chart_of_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chart of Accounts</relationshipLabel>
        <relationshipName>Chart_of_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metric</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Formula__c</fullName>
        <label>Formula</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Chart of Accounts</label>
    <nameField>
        <label>Chart of Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financials__c.object
<CustomObject>
    <fields>
        <fullName>Chart_of_Accounts_AccId__c</fullName>
        <formula>Chart_of_Accounts__r.Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Chart of Accounts AccId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chart_of_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chart of Accounts</label>
        <referenceTo>Chart_of_Accounts__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Report Period</label>
        <referenceTo>Report_Period__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financials</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Financials  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Report_Period__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Report Periods</relationshipLabel>
        <relationshipName>Report_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Report Period</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Report Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FF_CalculateFormulas.cls
public class FF_CalculateFormulas {
    public static boolean firstRun = true;
    
    public static void recalculate(String AccId){
        List <Chart_of_Accounts__c> allCharts = [select id, Name, Account__c, Category__c, Formula__c from Chart_of_Accounts__c where Account__c =: AccId];
        List <Report_Period__c> allPeriods = [select id from Report_Period__c where Account__c =: AccId];
        List <Financials__c> financialsForUpdate = new List <Financials__c>();
        
        Map <String, Financials__c> financialsMap = new Map <String, Financials__c>();
        Map <String, Decimal> financialsValuesMap = new Map <String, Decimal>();
        for (Financials__c fin: [select Id, Report_Period__c, Chart_of_Accounts__c,Chart_of_Accounts__r.name, Value__c  from Financials__c where Chart_of_Accounts_AccId__c  =: AccId.substring(0, 15)]){
            financialsMap.put('' + fin.Chart_of_Accounts__c + fin.Report_Period__c, fin);
            financialsValuesMap.put('' + fin.Chart_of_Accounts__r.name + fin.Report_Period__c, fin.Value__c);
        }
        
        for (Chart_of_Accounts__c chart: allCharts){
            if (chart.Category__c ==  'Metric' && chart.Formula__c != null){
                for (Report_Period__c period : allPeriods){
                    if (financialsMap.containsKey ('' + chart.Id + period.Id)){
                        Financials__c fin = financialsMap.get('' + chart.Id + period.Id);
                        String Condition = chart.Formula__c;
                        integer fieldsInResult = 0;
                        fieldsInResult  = Condition.countMatches('{');
                        for (integer j=0; j<fieldsInResult; j++){
                            String field='';
                            field = Condition.substring(Condition.indexOf('{')+1,Condition.indexOf('}'));
                            if (financialsValuesMap.containsKey ('' + field + period.Id)){
                                Condition = Condition.replaceFirst(field,String.ValueOf(financialsValuesMap.get ('' + field + period.Id)));
                            } else {
                                Condition = Condition.replaceFirst(field,'0');
                            }
                            Condition=Condition.replaceFirst('\\{','');
                            Condition=Condition.replaceFirst('\\}','');
                        }
                        Decimal resultRT = 0;
                        try {
                        	resultRT = new RT_Expression(Condition).eval();
                        } catch (exception e){}

                        fin.Value__c = resultRT;
                        financialsForUpdate.add(fin);
                    } else {
                        Financials__c fin = new Financials__c();
                        fin.Report_Period__c = period.Id;
                        fin.Chart_of_Accounts__c = chart.Id;
                        
                        String Condition = chart.Formula__c;
                        integer fieldsInResult = 0;
                        fieldsInResult  = Condition.countMatches('{');
                        for (integer j=0; j<fieldsInResult; j++){
                            String field='';
                            field = Condition.substring(Condition.indexOf('{')+1,Condition.indexOf('}'));
                            if (financialsValuesMap.containsKey ('' + field + period.Id)){
                                Condition = Condition.replaceFirst(field,String.ValueOf(financialsValuesMap.get ('' + field + period.Id)));
                            } else {
                                Condition = Condition.replaceFirst(field,'0');
                            }
                            Condition=Condition.replaceFirst('\\{','');
                            Condition=Condition.replaceFirst('\\}','');
                        }
                        Decimal resultRT = 0;
                        try {
                        	resultRT = new RT_Expression(Condition).eval();
                        } catch (exception e){}

                        fin.Value__c = resultRT;
                        financialsForUpdate.add(fin);
                    }
                    
                }
            }
        }

        upsert financialsForUpdate;
        
    }
}