src/objects/Document__c.object
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DocumentDownloadCount__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>DocumentDownloadCounts</relationshipLabel>
        <relationshipName>DocumentDownloadCounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>DocumentDownloadCount</label>
    <nameField>
        <displayFormat>DDC-{0000}</displayFormat>
        <label>DocumentDownloadCount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocumentDownloadCounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContentDownloadCustomHandlerFactory.cls
public class ContentDownloadCustomHandlerFactory implements Sfc.ContentDownloadHandlerFactory {
        public Sfc.ContentDownloadHandler getContentDownloadHandler(List<ID> ids, Sfc.ContentDownloadContext context) {
            Sfc.ContentDownloadHandler contentDownloadHandler = new Sfc.ContentDownloadHandler();
            List <id> ContentDocumentIds = new List <id>();
            for (ContentVersion cv : [SELECT Id, ContentDocumentId, ContentDocument.Title, ContentDocument.FileType FROM ContentVersion WHERE Id in: ids]){
                ContentDocumentIds.add(cv.ContentDocumentId);
            }
            
            List <DocumentDownloadCount__c> downloadsList = new List <DocumentDownloadCount__c>();

            if(ContentDocumentIds.size()>0){
                for(ContentDocumentLink cdl : [SELECT Id, LinkedEntityId FROM ContentDocumentLink WHERE ContentDocumentId in: ContentDocumentIds]) {
                    if(cdl.LinkedEntityId.getSObjectType() == Schema.Document__c.getSObjectType()) {
                        downloadsList.add(new DocumentDownloadCount__c(Document__c = cdl.LinkedEntityId));
                    }        
                }
            }
            insert downloadsList;
            contentDownloadHandler.isDownloadAllowed = true;       
            return contentDownloadHandler;
        }
    }