src/objects/Document__c.object
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DocumentViewCount__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>DocumentViewCounts</relationshipLabel>
        <relationshipName>DocumentViewCounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>DocumentViewCount</label>
    <nameField>
        <displayFormat>DVC-{00000}</displayFormat>
        <label>DocumentViewCount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocumentViewCounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LogFileView.cls
global with sharing class LogFileView {
    @RemoteAction
    global static void logView (String recId){
        system.debug(recId);
        List <DocumentViewCount__c> views = new List <DocumentViewCount__c>();
        for(ContentDocumentLink fileLink:  [select Id, LinkedEntityId, ContentDocumentId from ContentDocumentLink where ContentDocumentId =:recId]){
            if (fileLink.LinkedEntityId.getSObjectType().getDescribe().getName()=='Document__c') {
                views.add(new DocumentViewCount__c (Document__c = fileLink.LinkedEntityId));
            }

        }
        insert views;
    }
}