src/objects/Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DocumentDownloadCount__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>DocumentDownloadCounts</relationshipLabel>
        <relationshipName>DocumentDownloadCounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>DocumentDownloadCount</label>
    <nameField>
        <displayFormat>DDC-{0000}</displayFormat>
        <label>DocumentDownloadCount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocumentDownloadCounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DocumentViewCount__c.object
<CustomObject>
    <fields>
        <fullName>Document__c</fullName>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>DocumentViewCounts</relationshipLabel>
        <relationshipName>DocumentViewCounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>DocumentViewCount</label>
    <nameField>
        <displayFormat>DVC-{00000}</displayFormat>
        <label>DocumentViewCount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocumentViewCounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/docManFilesReportTest.cls
@isTest
public with sharing class docManFilesReportTest {
    @IsTest
    static void test(){

        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Document__c doc = new Document__c (Name__c='test',Account__c=acc.Id);
        insert doc;

        ContentVersion contentVersion = new ContentVersion(
          Title = 'test',
          PathOnClient = 'test.txt',
          VersionData = Blob.valueOf('test Content'),
          IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = doc.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;

        logFileView.logView(documents[0].Id);

        insert new DocumentViewCount__c(Document__c = doc.Id);
        insert new DocumentViewCount__c(Document__c = doc.Id);

        insert new DocumentDownloadCount__c(Document__c = doc.Id);
        insert new DocumentDownloadCount__c(Document__c = doc.Id);


        docManFilesReport.getDocs('Test Account',0,25);
        docManFilesReport.getNext(0,10);
        docManFilesReport.getPrevious(100,10);

    }

}