src/objects/Function__c.object
<CustomObject>
    <description>The field is used to track corporate events and invitees that have accepted, declined and attended the function.</description>
    <fields>
        <fullName>Begin_Date__c</fullName>
        <description>The date and time that the function starts.</description>
        <inlineHelpText>The date and time that the function starts.</inlineHelpText>
        <label>Begin Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The date and time that the function ends.</description>
        <inlineHelpText>The date and time that the function ends.</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Function_Status__c</fullName>
        <label>Function Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Function_Contact__c.object
<CustomObject>
    <description>Junction object to link contacts and corporate functions</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Function Contacts</relationshipLabel>
        <relationshipName>Function_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Function_Status__c</fullName>
        <description>Status of the person with respect to the corporate function.</description>
        <inlineHelpText>Status of the person with respect to the corporate function.</inlineHelpText>
        <label>Function Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Undecided</fullName>
                    <label>Undecided / No Response</label>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <referenceTo>Function__c</referenceTo>
        <relationshipLabel>Function Contacts</relationshipLabel>
        <relationshipName>Function_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Function Contact</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Function Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FunctionTriggerHandlerTest.cls
@isTest 
public with sharing class FunctionTriggerHandlerTest {
    
	static testMethod void testMethod1() {
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new FunctionTriggerHandlerMock());
        Function__c f = new Function__c();
        f.Name = 'test';
        f.Begin_Date__c = system.now();
        f.End_Date__c = system.now().addhours(1);
        f.Function_Status__c = 'Planned';
        insert f;
        

        account a = new account();
        a.name = 'test';
        insert a;

        Contact c = new Contact(LastName = 'test', accountId = a.Id, email = 'test@sddghghf.com');
        insert c;
        Function_Contact__c fc = new Function_Contact__c();
        fc.Contact__c = c.Id;
        fc.Function__c = f.Id;
        insert fc;

        FunctionTriggerHandler.sendinvitations(f.Id);
        Test.StopTest();

        FunctionTriggerHandler.getFunctionContactStatus(fc.Id); 
        FunctionTriggerHandler.addRegistrant(fc.Id);

        
    }
    static testMethod void testMethod2() {
        Test.setMock(HttpCalloutMock.class, new FunctionTriggerHandlerMock());
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        Function__c f = new Function__c();
        f.Name = 'test';
        f.Begin_Date__c = system.now();
        f.End_Date__c = system.now().addhours(1);
        f.Function_Status__c = 'Planned';
        insert f;
        

        account a = new account();
        a.name = 'test';
        insert a;

        Contact c = new Contact(LastName = 'test', accountId = a.Id, email = 'test@sddghghf.com');
        insert c;
        Function_Contact__c fc = new Function_Contact__c();
        fc.Contact__c = c.Id;
        fc.Function__c = f.Id;
        fc.registrant_id__c = 'test';
        insert fc;

        
        
        /*String json = '{'+
		'  \"event\": \"string\",'+
		'  \"event_ts\": \"long\",'+
		'  \"payload\": {'+
		'    \"objectCustom\": {'+
		'      \"participant\": {'+
		'        \"id\": \"string\"'+
		'      }'+
		'    }'+
		'  }'+
		'}';*/
        String json = '{"event":"meeting.participant_joined","payload":{"object":{"participant":{"id":"test"}}}}';
               
        req.requestURI = '/services/apexrest/zoomwebhooks'; 

        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(json);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
        ZoomRestResources.doPost();
        json = '{"event":"meeting.participant_left","payload":{"object":{"participant":{"id":"test"}}}}';
        req.requestBody = Blob.valueOf(json);
        RestContext.request = req;
        RestContext.response = res;
        ZoomRestResources.doPost();
        Test.stopTest();
    }

}