src/objects/Function__c.object
<CustomObject>
    <description>The field is used to track corporate events and invitees that have accepted, declined and attended the function.</description>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Function_Contact__c.object
<CustomObject>
    <description>Junction object to link contacts and corporate functions</description>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if the person actually attended the event.</description>
        <inlineHelpText>True if the person actually attended the event.</inlineHelpText>
        <label>Attended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <referenceTo>Function__c</referenceTo>
        <relationshipLabel>Function Contacts</relationshipLabel>
        <relationshipName>Function_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Join_Time__c</fullName>
        <label>Join Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Leave_Time__c</fullName>
        <label>Leave Time</label>
        <type>DateTime</type>
    </fields>
    <label>Function Contact</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Function Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZoomRestResources.cls
@RestResource(urlMapping='/zoomwebhooks')
global class ZoomRestResources {
    @HttpPost
    global static void doPost()
    {
        RestRequest req = RestContext.request;
        Blob body = req.requestBody;
        String bodyString = body.toString().replace('object','objectCustom');
        
        ZoomRestResources zr = (ZoomRestResources) JSON.deserialize(bodyString,ZoomRestResources.class);
        system.debug(zr.payload.objectCustom.participant.id);
        system.debug(zr.payload.objectCustom.id);
        system.debug(zr.event);

        if (zr.event == 'meeting.participant_joined'){
            try{
                Function_Contact__c fc = [select id from Function_Contact__c where function__r.Meeting_Id__c =: zr.payload.objectCustom.id and registrant_id__c = : zr.payload.objectCustom.participant.id and Join_Time__c = null order by createdDate desc limit 1];
                fc.Join_Time__c = System.Now();
                fc.Attended__c = true;
                update fc;
            } catch(exception e){

            }
        } else if (zr.event == 'meeting.participant_left'){
            try{
                Function_Contact__c fc = [select id from Function_Contact__c where function__r.Meeting_Id__c =: zr.payload.objectCustom.id and registrant_id__c = : zr.payload.objectCustom.participant.id order by createdDate desc  limit 1];
                fc.Leave_Time__c = System.Now();
                update fc;
            } catch(exception e){

            }
        }
        
    }
    

        public String event;
        public Payload payload;
    
        public class Participant {
            public String id;
        }
    
        public class ObjectCustom {
            public Participant participant;
            public String id;
        }
    
        public class Payload {
            public ObjectCustom objectCustom;
        }
    
        
        /*public static ZoomRestResources parse(String json) {
            return (ZoomRestResources) System.JSON.deserialize(json, ZoomRestResources.class);
        }*/
    
}