src/objects/Investment__c.object
<CustomObject>
    <fields>
        <fullName>Investor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investments made by investors (account type investor) linked to a particular round (which then links back to an account_type record = target).</description>
        <label>Investor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investments</relationshipLabel>
        <relationshipName>Investments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <referenceTo>Round__c</referenceTo>
        <relationshipLabel>Investments</relationshipLabel>
        <relationshipName>Investments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investment</label>
    <nameField>
        <displayFormat>INV{00000}</displayFormat>
        <label>Investment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <fields>
        <fullName>Round__c</fullName>
        <label>Series</label>
        <picklist>
            <picklistValues>
                <fullName>Seed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Series D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Shares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Options</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Company__c</fullName>
        <label>Target Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Investment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Series</label>
    <nameField>
        <displayFormat>Round{00000}</displayFormat>
        <label>Investment Series</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Series</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>CASESAFEID(Contact.AccountId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account_Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CommunityPageHeaderCtrl.cls
global without sharing class CommunityPageHeaderCtrl{
    @AuraEnabled
     public static objWrapper getInitValues (String recId){ 
         String sobjName = Id.valueOf(recId).getSObjectType().getDescribe().getName(); 
         
         DescribeSObjectResult objResult = Schema.getGlobalDescribe().get(sobjName).getDescribe();
         SObject record;
         String accID = null;
         String accName = null;
         String accDescription = null;
         String RecordType = null;
         
         if (sobjName=='Account'){
            record = Database.query('Select Name,Description, External_Logo__c,External_Logo2__c,External_Logo3__c, Recordtype.Name From ' + sobjName + ' Where Id = :recId');
            accDescription = String.ValueOf(record.get('Description')); /*!= null ? String.ValueOf(record.get('Description')) : ;*/
            RecordType = String.ValueOf(record.getSobject('Recordtype').get('Name'));
         } else if (sobjName=='Round__c') {
            record = Database.query('Select Name, Target_Company__c, Target_Company__r.Name, Target_Company__r.Recordtype.Name From ' + sobjName + ' Where Id = :recId');
            accID = String.ValueOf(record.get('Target_Company__c'));
            accName = String.ValueOf(record.getSobject('Target_Company__r').get('Name'));
            RecordType = String.ValueOf(record.getSobject('Target_Company__r').getSobject('Recordtype').get('Name'));
        } else if (sobjName=='Investment__c') {
            record = Database.query('Select Name, Investor__c, Investor__r.Name, Investor__r.Recordtype.Name From ' + sobjName + ' Where Id = :recId');
            accID = String.ValueOf(record.get('Investor__c'));
            accName = String.ValueOf(record.getSobject('Investor__r').get('Name'));
            RecordType = String.ValueOf(record.getSobject('Investor__r').getSobject('Recordtype').get('Name'));
         } else {
             try{
                 record = Database.query('Select Name, Account__c, Account__r.Name, Account__r.Recordtype.Name From ' + sobjName + ' Where Id = :recId');
                 accID = String.ValueOf(record.get('Account__c'));
                 accName = String.ValueOf(record.getSobject('Account__r').get('Name'));
                 RecordType = String.ValueOf(record.getSobject('Account__r').getSobject('Recordtype').get('Name'));
             } catch(exception e){
                 record = Database.query('Select Name, AccountId, Account.Name, Account.Recordtype.Name From ' + sobjName + ' Where Id = :recId');
                 accID = String.ValueOf(record.get('AccountId'));
                 accName = String.ValueOf(record.getSobject('Account').get('Name'));
                 RecordType = String.ValueOf(record.getSobject('Account').getSobject('Recordtype').get('Name'));
             }
         }
         

         objWrapper ow = new objWrapper(sobjName, String.ValueOf(record.get('Name')), accID, accName, accDescription, record, RecordType);
         return ow;
     }
    
    public class objWrapper {
        @AuraEnabled
        public String sobjName {get; set;}
        @AuraEnabled
        public String recordName {get; set;}
        @AuraEnabled
        public String accID {get; set;}
        @AuraEnabled
        public String accName {get; set;}
        @AuraEnabled
        public String accDescription {get; set;}
        @AuraEnabled
        public SObject obj {get; set;}
        @AuraEnabled
        public String RecordType {get; set;}
        @AuraEnabled
        public String UserAccountRT {get; set;}
        @AuraEnabled
        public String UserAccountName {get; set;}


        public objWrapper(String sobjName, String recordName, String accID, String accName, String accDescription, SObject obj, String RecordType){
            this.sobjName = sobjName;
            this.recordName = recordName;
            this.accID = accID;
            this.accName = accName;
            this.accDescription = accDescription;
            this.obj = obj;
            this.RecordType = RecordType;
            try {
                String userAccId = [select Account_Id__c from user where id =: userinfo.getuserid()].Account_Id__c;
                Account acc = [select Name,RecordType.Name from Account where id=: userAccId];
                this.UserAccountRT = acc.RecordType.Name;
                this.UserAccountName = acc.Name;
            } catch(exception e){}
            
        }
    }
}