src/objects/milestone__c.object
<CustomObject>
    <description>Milestones related so product delivery or sales efforts. These can also be firm objectives.</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CustomMilestoneCreateControllerTest.cls
@isTest
public class CustomMilestoneCreateControllerTest {
    static testMethod void testMethod1() {
        string s = CustomMilestoneCreateController.getAccountId();
        Account a = new Account (name='test');
        insert a;
        milestone__c ms = new milestone__c();
        ms.name='test';
        ms.Company__c=a.id;
        s = CustomMilestoneCreateController.saveRecordContr (JSON.serialize(ms));
	}
}