src/objects/milestone__c.object
<CustomObject>
    <description>Milestones related so product delivery or sales efforts. These can also be firm objectives.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>CASESAFEID(Contact.AccountId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account_Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CustomMilestoneCreateController.cls
public without sharing class  CustomMilestoneCreateController {
	
    @AuraEnabled
     public static String getAccountId(){
         return [select Account_Id__c from User where id=:Userinfo.getUserId()].Account_Id__c;
     }
    @AuraEnabled
     public static String saveRecordContr(String MSrec){
         try{
             system.debug(MSrec);
             MSrec=MSrec.replace('[','').replaceAll(']','');
             system.debug(MSrec);
             milestone__c ms = (milestone__c)JSON.deserialize(MSrec,milestone__c.class);
             
            insert ms;
            return ms.Id;
         }catch(exception e){
            throw new AuraHandledException('Error: ' + e.getMessage());   
         }
         //return '';
     }
}