src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead_Investor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Investor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Fintech, Portfolio Company</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals (Lead Investor)</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loss_Reason__c</fullName>
        <label>Loss Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>No Budget / Lost Funding</fullName>
                </value>
                <value>
                    <fullName>No Decision / Non-Responsive</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pass_Reason__c</fullName>
        <label>Pass Reason Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Total_Raise__c</fullName>
        <label>Total Raise</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>CASESAFEID(Contact.AccountId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account_Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CommunityDeals.cls
public without sharing class CommunityDeals {
	@AuraEnabled  
    public static List<Opportunity> getFilteredDeals(){
        List <Opportunity> opp = new List <Opportunity>();
        string accId = [select id, Account_Id__c from user where id =: userInfo.getUserId()].Account_Id__c;
        opp = [select id, Name,Amount,CloseDate,StageName,Probability,Type,LeadSource,AccountId,Account.Name, Owner.alias  from Opportunity where AccountId=:accId order by CreatedDate desc limit 1000];
        return opp;
    }
    
    @AuraEnabled
    public static map<String,String> getOppMap(String dealId){
        Map<String,String> DealObj = new Map<String,String>();
        Opportunity opp = [select Name, Owner.Name,Account.Name,CloseDate,Type,StageName,Campaign.Name,Probability,
                           Loss_Reason__c, Amount,Pass_Reason__c,Total_Raise__c,Lead_Investor__r.name,NextStep,LeadSource,
                           Description,CreatedDate,CreatedBy.Name,LastmodifiedDate,LastmodifiedBy.Name from Opportunity where id=:dealId];
        DealObj.put('Name',opp.Name);
        DealObj.put('OwnerId',opp.Owner.Name);
        DealObj.put('AccountName',opp.Account.Name);
        DealObj.put('CloseDate',String.ValueOf(opp.CloseDate));
        DealObj.put('Type',opp.Type);
        DealObj.put('StageName',opp.StageName);
        DealObj.put('CampaignName',opp.Campaign.Name);
        DealObj.put('Probability',String.ValueOf(opp.Probability));
        DealObj.put('Loss_Reason__c',opp.Loss_Reason__c);
        DealObj.put('Amount',String.ValueOf(opp.Amount));
        DealObj.put('Pass_Reason__c',opp.Pass_Reason__c);
        DealObj.put('Total_Raise__c',String.ValueOf(opp.Total_Raise__c));
        DealObj.put('Lead_Investor__c',opp.Lead_Investor__r.name);
        DealObj.put('NextStep',opp.NextStep);
        DealObj.put('LeadSource',opp.LeadSource);
        DealObj.put('Description',opp.Description);
        DealObj.put('CreatedBy',opp.CreatedBy.Name + ', ' + opp.CreatedDate);
        DealObj.put('LastmodifiedBy',opp.LastmodifiedBy.Name + ', ' + opp.LastmodifiedDate);
        
        
        return DealObj;
      }

}