src/objects/Related_Account__c.object
<CustomObject>
    <fields>
        <fullName>Child__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parent Accounts</relationshipLabel>
        <relationshipName>Child_Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Companies</relationshipLabel>
        <relationshipName>Related_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Investment Manager</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Related Account</label>
    <nameField>
        <displayFormat>RA - {00000}</displayFormat>
        <label>Related Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RelatedCompaniesController.cls
public with sharing class RelatedCompaniesController {
    @AuraEnabled
    public static List<Related_Account__c> getAccounts(String recId){
        //return [select id, Name, Type, External_Logo__c, External_Logo2__c, External_Logo3__c from Account where id in (select Child__c from Related_Account__c where Parent__c =: recId)];
        return [select Relationship__c, Child__c, Child__r.Name, Child__r.External_Logo__c, Child__r.External_Logo2__c, Child__r.External_Logo3__c from Related_Account__c where Parent__c =: recId];
        
    }
}