src/objects/ReportSubscription__c.object
<CustomObject>
    <fields>
        <fullName>ReportId__c</fullName>
        <label>ReportId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Name__c</fullName>
        <label>Report Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscribed__c</fullName>
        <label>Subscribed</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                    <default>true</default>
                    <label>Unsubscribed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ReportSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ReportSubscription</label>
    <nameField>
        <displayFormat>RS- {0000}</displayFormat>
        <label>ReportSubscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ReportSubscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReportShedulerDaily.cls
global class ReportShedulerDaily implements Schedulable {
   global void execute(SchedulableContext sc) {
      
        EmailTemplate emailTemplate = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where name = 'DailyReports'];

        List <Messaging.SingleEmailMessage> messages = new List <Messaging.SingleEmailMessage>();

        Map <Id,Report> reps= new Map <Id,Report>([select id, Name from Report]);
        List <ReportSubscription__c> rsl = [select Id, ReportId__c from ReportSubscription__c ];
        for (ReportSubscription__c rs: rsl){
            rs.Report_Name__c = reps.get(rs.ReportId__c).Name;
        }
        update rsl;


        for (ReportSubscription__c rs: [select User__c, ReportId__c, Id from ReportSubscription__c where Subscribed__c = 'Daily']){
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setTargetObjectId(rs.User__c); 
            message.setSenderDisplayName('Canapi Connect'); 
            message.setUseSignature(false); 
            message.setBccSender(false); 
            message.setSaveAsActivity(false); 
            message.setTemplateID(emailTemplate.Id); 
            message.setWhatId(rs.Id); 
            messages.add(message);
        }

        if (messages.size() > 0){
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        }

    }
}