src/objects/ReportSubscription__c.object
<CustomObject>
    <fields>
        <fullName>Subscribed__c</fullName>
        <label>Subscribed</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                    <default>true</default>
                    <label>Unsubscribed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ReportSubscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ReportSubscription</label>
    <nameField>
        <displayFormat>RS- {0000}</displayFormat>
        <label>ReportSubscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ReportSubscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReportShedulerMonthly.cls
global class ReportShedulerMonthly implements Schedulable {
   global void execute(SchedulableContext sc) {
      
        EmailTemplate emailTemplate = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where name = 'MonthlyReports'];
        Set <Id> usersIds = new Set <Id>();

        for (ReportSubscription__c rs: [select User__c from ReportSubscription__c where Subscribed__c = 'Monthly']){
            usersIds.add(rs.User__c);
        }

        List <Messaging.SingleEmailMessage> messages = new List <Messaging.SingleEmailMessage>();

        for (id Uid: usersIds){
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTargetObjectId(Uid); 
        message.setSenderDisplayName('Canapi Connect'); 
        message.setUseSignature(false); 
        message.setBccSender(false); 
        message.setSaveAsActivity(false); 
        message.setTemplateID(emailTemplate.Id); 
        message.setWhatId(Uid); 
        messages.add(message);
        }
        if (messages.size() > 0){
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        }

        }
}