src/objects/Terms_of_Service__mdt.object
<CustomObject>
    <fields>
        <fullName>HTML_code__c</fullName>
        <label>HTML code</label>
        <length>100768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Terms of Service</label>
    <pluralLabel>Terms of Service</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Accepted_Terms__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepted Terms</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TermsOfService.cls
public without sharing class TermsOfService {
    @AuraEnabled
    public static TermsWrapper getTermsState (){

        Boolean termsState = [select Accepted_Terms__c from User where id =: UserInfo.getUserId()].Accepted_Terms__c;
        String terms = [select HTML_code__c from Terms_of_Service__mdt limit 1].HTML_code__c;
        return new TermsWrapper (termsState, terms);
    }

    @AuraEnabled
    public static void acceptTerms (){
        User u = new User (id = UserInfo.getUserId(), Accepted_Terms__c = true);
        update u;
    }

    public class TermsWrapper {
        @AuraEnabled public boolean TermsState { get; set;}
        @AuraEnabled public String Terms { get; set;}
        public TermsWrapper (boolean TermsState, String Terms){
            this.TermsState = TermsState;
            this.Terms = Terms;
        }
    }

}