src/objects/UserContactTagAssociation__c.object
<CustomObject>
    <fields>
        <fullName>UserContactTag__c</fullName>
        <label>UserContactTag</label>
        <referenceTo>UserContactTag__c</referenceTo>
        <relationshipLabel>UserContactTagAssociations</relationshipLabel>
        <relationshipName>UserContactTagAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserContactTagAssociations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserContactTagAssociation</label>
    <nameField>
        <displayFormat>UCTA-{0000}</displayFormat>
        <label>UserContactTagAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserContactTagAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AllianceConnectionsControllerTest.cls
@isTest public class AllianceConnectionsControllerTest {
    static testMethod void testMethod1() {
        UserContactTag__c tag = new UserContactTag__c(Name = 'Test',Hierarchy_Level__c = 1);
        insert tag;
        UserContactTagAssociation__c ucta = new UserContactTagAssociation__c();
        ucta.User__c = UserInfo.getUserId();
        ucta.UserContactTag__c = tag.Id;
        insert ucta;
        AllianceConnectionsController.getContacts('test','Name');
    }
}