src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>CASESAFEID(Contact.AccountId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account_Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UserContactTagAssociation__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserContactTagAssociations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserContactTagAssociation</label>
    <nameField>
        <displayFormat>UCTA-{0000}</displayFormat>
        <label>UserContactTagAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserContactTagAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/communityVerticalNavCtrl.cls
public with sharing class communityVerticalNavCtrl {

    @AuraEnabled
    public static navWrapper getSettings(){
        List <CollaborationGroup> groups = [SELECT Id,Name	FROM CollaborationGroup WHERE NetworkId =: Network.getNetworkId() and CollaborationType = 'Public' and IsArchived = false order by Name asc];
        boolean  hasTags = [select id from UserContactTagAssociation__c where User__c =: UserInfo.getUserId()].size() > 0;
        String accId;
        accId = [select id,Account_Id__c from user where id=:UserInfo.getUserId()].Account_Id__c;
       
        if (accId == null){
            accId = [select id from Account where Name = 'Canapi' limit 1].Id;
        }
        String RecTypeName = [select recordtype.name from Account where id =:accId].recordtype.name;
        return new navWrapper(groups, hasTags, RecTypeName, accId);
        
    }

    public class navWrapper{
        @AuraEnabled public List <CollaborationGroup> groups {get;set;}
        @AuraEnabled public String recTypeName {get;set;}
        @AuraEnabled public Boolean hasTags {get;set;}
        @AuraEnabled public String accId {get;set;}
        public navWrapper (List <CollaborationGroup> groups, Boolean hasTags, String recTypeName, String accId){
            this.groups = groups;
            this.hasTags = hasTags;
            this.recTypeName = recTypeName;
            this.accId = accId;
        }
    }
}