src/objects/VC_Template__mdt.object
<CustomObject>
    <description>Used for storing Vendor Catalog List</description>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name (Row name)</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type (header)</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Vendor Catalog Item</label>
    <pluralLabel>Vendor Catalog Items</pluralLabel>
</CustomObject>

src/objects/Vendor_Catalog__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Catalog</relationshipLabel>
        <relationshipName>Vendor_Catalog</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name (Row name)</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type (Header)</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Vendor Catalog</label>
    <nameField>
        <displayFormat>VC- {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VC_MainCatalogControllerTest.cls
@IsTest public class VC_MainCatalogControllerTest {
	@IsTest
    private static void testgetCapTableData() {
        account a = new account(name='test');
        insert a;
    	
        VC_Template__mdt VCTemplate = new VC_Template__mdt ();
        VCTemplate.Name__c = 'test';
        VCTemplate.Type__c = 'test';
        
        VC_MainCatalogController.getCatalogMap(a.Id);
        
        Vendor_Catalog__c vc = new Vendor_Catalog__c(Name__c ='test', Type__c = 'test', Account__c = a.id);
        insert vc;
        
        VC_MainCatalogController.updateVendor(vc.Id,a.Id);
        
        VC_MainCatalogController.getInitialSettings(a.Id);
        VC_MainCatalogController.getInitialSettings(null);
    }
        
}